graphql:
  playground:
    headers:
      Authorization: Bearer TOKEN
    tabs:
      - name: Bank Account Query
        query: classpath:playground/bank_account.graphql
        variables: classpath:playground/bank_account_variables.json